api/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register('languages', views.LanguageView)
router.register('company', views.CompanyView)
router.register('employee', views.EmployeeView)

urlpatterns = [
    path('', include(router.urls))
]

newproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('api/', include('api.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup', views.signup, name='signup'),
    path('signin', views.signin, name='signin'),
    path('logoutUser', views.logoutUser, name='logoutUser'),
    path('groupA', views.groupA, name='groupA'),
    path('groupB', views.groupB, name='groupB'),
    path('index', views.index, name='index')
]

api/models.py
from django.db import models

# Create your models here.

class Company(models.Model):
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name

class Employee(models.Model):
    name = models.CharField(max_length=30)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    languages= models.ManyToManyField(Language)
    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    group = models.CharField(max_length=30, blank=True)
    def __str__(self):
        return self.user

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    CHOICES = (('A', 'A'),('B', 'B'))
    group = forms.ChoiceField(choices=CHOICES)

    class Meta:
        model = User
        fields = ('username', 'group', 'password1', 'password2')

class SignInForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)

api/views.py
from django.shortcuts import render
from .models import Language, Employee, Company
from .serializers import LanguageSerializer, CompanySerializer, EmployeeSerializer
from rest_framework import viewsets, permissions
from .permissions import UserGroupPermissions

# Create your views here.
class LanguageView(viewsets.ModelViewSet):
    queryset = Language.objects.all()
    serializer_class = LanguageSerializer
    permission_classes = (UserGroupPermissions,)

class CompanyView(viewsets.ModelViewSet):
    queryset = Company.objects.all()
    serializer_class = CompanySerializer
    permission_classes = (UserGroupPermissions,)

class EmployeeView(viewsets.ModelViewSet):
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer
    permission_classes = (UserGroupPermissions,)

users/views.py
import json

from django.contrib.auth  import login, authenticate, logout
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.http import HttpResponse, JsonResponse
from .forms import SignUpForm, SignInForm
from .decorators import login_required, login_required_groupA, login_required_groupB, logout_required

# View functions

@logout_required
def home(request):
    return render(request, 'users/home.html')

@logout_required
def signup(request):
    if request.method =='POST':
        form = SignUpForm(request.POST)
        # print(form)
        print(request.POST)
        print(form.is_valid())
        if form.is_valid():
            user = form.save()
            print(user)
            user.refresh_from_db()
            user.profile.group = form.cleaned_data.get('group')
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('users:index')
        else:
            print("error")
    form = SignUpForm()
    return render(request, 'users/signup.html', {'form': form})

@logout_required
def signin(request):
    if request.method == 'POST':
        form = SignInForm(request.POST)
        print(form.is_valid())
        if form.is_valid():
            find_user = User.objects.get(username=request.POST['username'])
            user = authenticate(username=find_user.username, password=request.POST['password'])
            login(request, user)
            return redirect('users:index')
        else:
            print("error")
    form = SignInForm()
    return render(request, 'users/signin.html', {'form': form})

@login_required_groupA
def groupA(request):
    return render(request, 'users/groupA.html')

@login_required_groupB
def groupB(request):
    return render(request, 'users/groupB.html')

@login_required
def index(request):
    if request.user.profile.group=='A' or request.user.is_staff==True:
        return redirect('users:groupA')
    return redirect('users:groupB')

@login_required
def logoutUser(request):
    logout(request)
    return redirect('users:home')

templates/users/groupA.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Group A</title>
    <!--bootstrap-->
    <link rel="stylesheet" href="{% static 'users/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'users/css/generic.css' %}">
    <link rel="stylesheet" href="{% static 'users/css/groupA.css' %}">
</head>
<body>
    <div class="container">
        <div class="jumbotron">
            <center><h2>Group A</h2></center><hr>
            <center><a href="{% url 'api-root' %}"><button type="button" class="btn btn-danger">Go To API</button></a>&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="{% url 'users:logoutUser' %}"><button class="btn btn-danger">Logout</button></a></center>
        </div>
    </div>
</body>
</html>

templates/users/groupB.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Group B</title>
    <!--bootstrap-->
    <link rel="stylesheet" href="{% static 'users/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'users/css/generic.css' %}">
    <link rel="stylesheet" href="{% static 'users/css/groupB.css' %}">
</head>
<body>
    <div class="container">
        <div class="jumbotron">
            <center><h2>Group B</h2></center><hr>
            <center><a href="{% url 'api-root' %}"><button type="button" class="btn btn-danger">Go To API</button></a> &nbsp;&nbsp;&nbsp;&nbsp;
            <a href="{% url 'users:logoutUser' %}"><button class="btn btn-danger">Logout</button></a></center>
        </div>
    </div>
</body>
</html>

templates/users/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Getting Started</title>
    <!--bootstrap-->
    <link rel="stylesheet" href="{% static 'users/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'users/css/generic.css' %}">
</head>
<body>
    <div class="container">
        <div class="jumbotron">
            <center>
                <h1>Welcome to website!</h1>
            </center><br><br><hr><br>
            <center>
            <a href="{% url 'users:signin' %}"><button type="button" class="btn btn-primary">Login</button></a>&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="{% url 'users:signup' %}"><button type="button" class="btn btn-success">Register</button></a>
            </center>
        </div>
    </div>
    <center>
        <ul>
            <h6>To access /api route, you must be authenticated!</h2>
        </ul>
    </center>
</body>
</html>

templates/users/signin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Signup</title>
    <!--bootstrap-->
    <link rel="stylesheet" href="{% static 'users/css/bootstrap.min.css' %}">
</head>
<body>
    <div class="container">
        <div class="jumbotron">
            <div class="container">
                <center><h1>SignIn!</h1></center>
            </div>
        </div>
        <div class="container">
            <center>
            Group A : Users can ammend and view the api.<br>
            Group B : Users can only view the api.<br>
            NOTE : superusers are naturally granted group A access<br>
            <br><br>

            </center>
        </div>
        <div class="container">
            <form action="{% url 'users:signin' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">LogIn!</button>
                <a href="{% url 'users:home' %}"><button type="button" class="btn btn-primary">Back</button></a>
            </form>
        </div>
    </div>
</body>
</html>

templates/users/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Signup</title>
    <!--bootstrap-->
    <link rel="stylesheet" href="{% static 'users/css/bootstrap.min.css' %}">
    <!--jquery-->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container">
        <div class="jumbotron">
            <div class="container">
                <center><h1>SignUp!</h1></center>
            </div>
        </div>
        <div class="container">
            <center>
            Group A : Users can ammend and view the api.<br>
            Group B : Users can only view the api.<br>
            NOTE : superusers are naturally granted group A access<br>
            <br><br>

            </center>
        </div>
        <div class="container">
            <div class="messgae"></div>
            <form action="{% url 'users:signup' %}" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Register!</button>
                <a href="{% url 'users:home' %}"><button type="button" class="btn btn-primary">Back</button></a>
            </form>
        </div>
    </div>
</body>
<!-- <script>
    $(document).ready(function() {
        $('form').on("submit", function(event){
            event.preventDefault();
            var signup_url = "{% url 'users:signup' %}";
            $.ajax({
                url : signup_url,
                method: 'POST',
                data: $(this).serialize(),
                datatype: 'json',
                success: function(data) {
                    $(".message")
                },
                error: function(data) {
                    
                }
            });
        });
    });
</script> -->
</html>